(ns little-paint-and-wonder.core
  (:require [reagent.core :as r] [reagent.dom.client :as rdom]))

(def instagram-url "https://www.instagram.com/littlepaintandwonder?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==")
(defonce app-state (r/atom {:page :home :theme (or (.getItem js/localStorage "lpw-theme") "light") :menu-open? false :sent? false}))
(def nav-items [[:home "Home"] [:safety "Safety & care"] [:connect "Let’s connect"]])
(defn icon [name] (let [paths {:sun "M12 3v2m0 14v2M3 12h2m14 0h2m-3.6-5.6-1.4 1.4M7 17l-1.4 1.4m0-12 1.4 1.4M17 17l1.4 1.4" :moon "M20 15.5A8.5 8.5 0 0 1 8.5 4 8.5 8.5 0 1 0 20 15.5Z" :instagram "M7 2h10a5 5 0 0 1 5 5v10a5 5 0 0 1-5 5H7a5 5 0 0 1-5-5V7a5 5 0 0 1 5-5Zm9.5 9.4a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0ZM18 6.2h.01" :arrow "M5 12h14m-6-6 6 6-6 6" :up "M12 19V5m-6 6 6-6 6" :menu "M4 7h16M4 12h16M4 17h16" :shield "M12 3 20 6v5c0 5-3.4 8.5-8 10-4.6-1.5-8-5-8-10V6l8-3Z" :heart "M12 20S4 15 4 9.5A4.5 4.5 0 0 1 12 6a4.5 4.5 0 0 1 8 3.5C20 15 12 20 12 20Z"}] [:svg.icon {:viewBox "0 0 24 24" :aria-hidden true :fill (if (= name :heart) "currentColor" "none") :stroke "currentColor" :stroke-width "1.8" :stroke-linecap "round" :stroke-linejoin "round"} [:path {:d (get paths name)}]]))
(defn go! [page] (swap! app-state assoc :page page :menu-open? false) (.scrollTo js/window #js {:top 0 :behavior "smooth"}))
(defn brand [] [:button.brand {:on-click #(go! :home) :aria-label "Little Paint & Wonder home"} [:img {:src "/assets/brand-logo.png" :alt "Little Paint & Wonder"}]])
(defn theme-toggle [] [:button.icon-button {:on-click #(let [next (if (= "light" (:theme @app-state)) "dark" "light")] (.setItem js/localStorage "lpw-theme" next) (swap! app-state assoc :theme next)) :aria-label "Toggle colour theme"} [icon (if (= "light" (:theme @app-state)) :moon :sun)]])
(defn header [] [:header.site-header [:div.wrap.header-inner [brand] [:nav.desktop-nav {:aria-label "Main navigation"} (for [[id label] nav-items] ^{:key (name id)} [:button {:class (when (= id (:page @app-state)) "active") :on-click #(go! id)} label])] [:div.header-actions [theme-toggle] [:a.instagram-link {:href instagram-url :target "_blank" :rel "noreferrer" :aria-label "Follow Little Paint & Wonder on Instagram"} [icon :instagram]] [:button.menu-button {:on-click #(swap! app-state update :menu-open? not) :aria-label "Open navigation"} [icon :menu]]] (when (:menu-open? @app-state) [:nav.mobile-nav {:aria-label "Mobile navigation"} (for [[id label] nav-items] ^{:key (name id)} [:button {:on-click #(go! id)} label])])]])
(defn hero [] [:section.hero [:div.wrap.hero-grid [:div.hero-copy [:p.eyebrow "A little bit of wonder"] [:h1 "Create, paint" [:br] "and " [:em "wonder."]] [:p.lead "Every Little Paint & Wonder creation starts as a blank canvas. Choose your colours, add your creativity, and make something completely your own."] [:div.hero-actions [:button.button.primary {:on-click #(go! :safety)} "Safety & care" [icon :arrow]] [:a.text-link {:href instagram-url :target "_blank" :rel "noreferrer"} "Follow our creations"]] [:div.trust-row [icon :heart] [:p [:strong "Made with love in Australia"] "Craft activities for little creators aged 3+."]]] [:div.hero-art {:aria-label "Little Paint & Wonder logo artwork"} [:img {:src "/assets/brand-logo.png" :alt ""}] [:span.hero-sticker "Made in" [:br] "Australia"]]]])
(defn story [] [:section.intro.wrap [:p.eyebrow "A small creative studio"] [:h2 "A world for little hands and big imaginations."] [:p "We make keepsake craft activities that let children play with colour, discover their own ideas and create something they can be proud of. Every kit is prepared with love in Australia."] [:div.value-cards [:article [icon :heart] [:h3 "Choose your colours"] [:p "Bring your own palette, personality and point of view."]] [:article [icon :shield] [:h3 "Create with care"] [:p "Simple material and safety guidance is always close by."]] [:article [icon :sun] [:h3 "Coming soon"] [:p "Online ordering and e-commerce are on their way — watch this space."]]]])
(def paints [{:title "Washable poster paint" :note "ED Art Supplies" :copy "Water-based, washable poster paint for artful afternoons."} {:title "Gyprock casting plaster" :note "Materials" :copy "Used to make decorative plaster creations that dry into special keepsakes."}])
(def safety-points ["Recommended for ages 3+ with adult supervision." "This is a craft activity — not intended as a toy." "Do not eat or place plaster or paint in the mouth." "Small pieces may present a choking hazard." "Plaster may break if dropped — handle with care." "Use paint as directed and keep away from eyes and mouth." "Allow your creation to dry completely before handling or displaying." "Please retain this information for future reference."])
(defn safety []
  [:section.content-section.safety {:id "safety"}
   [:div.wrap
    [:div.section-heading [:p.eyebrow "Safety & care"] [:h2 "The grown-up corner"] [:p "A few simple notes help all the creative fun stay happy, safe and easy. Materials, paint and plaster guidance are all gathered here for future reference."]]
    [:div.materials-grid
     [:article.material-card [:div.material-icon "✦"] [:p.label "Materials"] [:h3 "What’s inside"] [:ul (for [{:keys [title note copy]} paints] ^{:key title} [:li [:strong title] [:span note] [:p copy]])]]
     [:article.safety-card [:div.card-icon [icon :shield]] [:h3 "Safety & care"] [:ul (for [point safety-points] ^{:key point} [:li point])]]]
    [:div.first-aid
     [:article [icon :heart] [:h3 "Painting care"] [:p "Wash hands after painting. Protect clothing and surfaces from paint, and keep containers closed when not in use."]]
     [:article [icon :shield] [:h3 "If paint gets in eyes"] [:p "Rinse thoroughly with clean water. If irritation continues or you are concerned, seek medical advice."]]
     [:article [icon :sun] [:h3 "Plaster dust"] [:p "Do not dry-sand plaster around children. Any sanding, cutting or finishing should be done by an adult."]]]]])
(defn connect [] [:section.connect {:id "connect"} [:div.wrap.connect-grid [:div [:p.eyebrow "Let’s connect"] [:h2 "New creations, ideas and inspiration."] [:p "Follow along on Instagram for colourful little makes and updates as our online shop comes to life."] [:a.button.primary {:href instagram-url :target "_blank" :rel "noreferrer"} [icon :instagram] " @littlepaintandwonder"] [:p.coming "Online ordering is coming soon."]] [:a.qr-card {:href instagram-url :target "_blank" :rel "noreferrer" :aria-label "Open Little Paint and Wonder on Instagram"} [:img {:src "/assets/instagram-qr.png" :alt "QR code for Little Paint and Wonder Instagram"}] [:span "Scan to follow"]]]])
(defn updates [] [:section.updates [:div.wrap.updates-inner [:div [:p.eyebrow "Get updates"] [:h2 "A little wonder in your inbox."] [:p "Be first to know when online ordering opens, plus get gentle creative prompts and studio notes."]] [:form.subscribe {:on-submit (fn [e] (.preventDefault e) (swap! app-state assoc :sent? true))} [:label.sr-only {:for "email"} "Email address"] [:input {:id "email" :type "email" :required true :placeholder "Your email address"}] [:button.button.primary {:type "submit"} (if (:sent? @app-state) "You’re on the list!" "Get updates")]]]])
(defn footer [] [:footer.site-footer [:div.wrap.footer-inner [brand] [:p "Little Paint & Wonder · Made with love in Australia"] [:a.footer-insta {:href instagram-url :target "_blank" :rel "noreferrer"} [icon :instagram] " Instagram"] [:button.back-top {:on-click #(.scrollTo js/window #js {:top 0 :behavior "smooth"})} [icon :up] " Back to top"]]])
(defn page-content [] (case (:page @app-state) :home [:<> [hero] [story] [safety] [connect] [updates]] :safety [:<> [safety] [connect] [updates]] :connect [:<> [connect] [updates]]))
(defn app [] [:main {:class (str "app theme-" (:theme @app-state))} [header] [page-content] [footer] [:button.floating-top {:on-click #(.scrollTo js/window #js {:top 0 :behavior "smooth"}) :aria-label "Back to top"} [icon :up]]])
(defn init [] (let [root (rdom/create-root (.getElementById js/document "app"))] (rdom/render root [app])))
